import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import BugButton from "@/components/bug-button";
import BugButtonGrid from "@/components/bug-button-grid";
import BugDetailPopup from "@/components/bug-detail-popup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Bug Report</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h1>Bug report</h1>
          <BugDetailPopup></BugDetailPopup>
          <BugButtonGrid></BugButtonGrid>
        </main>
        {/* <footer className={styles.footer}>
        </footer> */}
      </div>
    </>
  );
}
